### ISSUE TITLE
Question: Is there any way to ignore some tags?

### ISSUE THREAD

**Issue by davesnx** [pveyes/htmr#111]
Hello @pveyes 

I'm trying to avoid to transform some HTML tags, something like:

```
const transform = {
	iframe: null,
    image: null
}
```

Since at the end it's running: `React.createElement()`. Is there any way to not transform into a component but still remain the children HTML?

I might do `iframe: div` and would do the trick, but isn't ideal or even transform to `React.Fragment`.

Thanks!

**Comment by pveyes** [comment]
Hi @davesnx what do you mean by `not transform into a component but still remain the children HTML?`

If you don't want to use custom transform, you can simply omit the transform option

```js
import htmr from 'htmr';

const result = htmr(html)
```

If you want to remove it from child you can pass function component that renders null

```js
import htmr from 'htmr';

const transform = {
  iframe: () => null
}
const result = htmr(html, { transform })
```

**Comment by davesnx** [comment]
Yep, that make sense!
