### ISSUE TITLE
Empty String Converted to `true`, Causing React Warning

### ISSUE THREAD

**Issue by mutewinter** [pveyes/htmr#136]
# Test Case

```
<p class="">Test</p>
```

# Error

```
react-dom.development.js?f8c1:67 Warning: Received `true` for a non-boolean attribute `className`.

If you want to write it to the DOM, pass a string instead: className="true" or className={value.toString()}.
```

# Expected Outcome

Just pass the empty string through (or omit `className` entirely).

**Comment by pveyes** [comment]
Thanks for the detailed issue

Based on HTML spec https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes, empty string is treated as a boolean attribute. htmr will treat the attribute as such, and forward the boolean value to react instead. See #103 

If you want to opt-out of this behavior, you can use custom transform, for example:

```js
htmr(html, {
  transform: {
    p: props => {
      if (props.className === '') delete props.className
      return <p {...props} />
    }
  }
})
