### ISSUE TITLE
Support react 18

### ISSUE THREAD

**Issue by iamyuu** [pveyes/htmr#143]

**Comment by pveyes** [comment]
Did you find any breakage? Is there any repro case I can take a look? If not I'll probably close this issue

**Comment by iamyuu** [comment]
it's working with react 18 🎉 (but need to update the [`peerDependencies`](https://github.com/pveyes/htmr/blob/master/package.json#L56))

**Comment by havran** [comment]
> Did you find any breakage? Is there any repro case I can take a look? If not I'll probably close this issue

Hi @pveyes, we use HTMR in production NextJS project and works without problems with React 18. Can you please update peerDependencies version for React? Currently when we use latest npm v8.11.0 we get error when we install packages (`npm ci`). 
We must use `npm -ci --legacy-peer-deps`.

**Comment by pveyes** [comment]
published in v1.0.2
