### ISSUE TITLE
Text node preprocessor

### ISSUE THREAD

**Issue by pveyes** [pveyes/htmr#23]
Currently we have no way of doing string transformation before render (for example to remove all whitespace after #22), unlike DOM node which can be mapped over using 2nd argument. Maybe we can also use it as mapping. Still not sure about the syntax, possibly empty string?

```js
convert(html, { '': str => str.trim() }
```

**Comment by greggb** [comment]
Almost seems like an options object would be useful if there will be additional transforms down the line.  Would need to be a major release.
```
convert(html, {
	map: {},
	trim: <bool>,
	etc...
 }
```

**Comment by pveyes** [comment]
Yeah I think I'm going to use option object for future version. Not sure about the trim option though because it seems limiting. Generic string processing can be useful to allow htmr to be rendered using react-native (which can't render string without `<Text>` component)

I'm learning ReasonML right now and I was inspired by their pattern matching syntax. I think we can use it as generic element preprocessor

Using react native transform as example
```js
let element = convert(html, {
  map: {
    div: View,
    _: (Component, props) => typeof Component === 'string'
      ? <Text>{el}</Text>
      : <Component {...props />
  }
});
```
