### ISSUE TITLE
Microbundle

### ISSUE THREAD

**Issue by greggb** [pveyes/htmr#27]
Have you looked at [microbundle](https://github.com/developit/microbundle) at all? Did a quick test and the output is tiny.

_microbundle on top:_
<img width="634" alt="screen shot 2018-01-23 at 10 52 03 pm" src="https://user-images.githubusercontent.com/514026/35313780-4eb31776-0090-11e8-931a-44d8b5a00398.png">

**Comment by pveyes** [comment]
Wow nice results! I've heard of it but haven't had a chance to look at it

Is there any trade off than using rollup?

**Comment by greggb** [comment]
It's a little more verbose in package.json - you need a call per entry, i.e. `microbundle -i browser.js && microbundle -i server.js`

I also had errors when bundling `server.js`, so I just ran the browser file. This may be an issue with some of the transforms in rollup.

Maybe not enough gains to make a change, but if you're interested I could open a PR when I debug `server.js`
