### ISSUE TITLE
Broken server side build using webpack module

### ISSUE THREAD

**Issue by pveyes** [pveyes/htmr#32]
Seems like ES modules support from #20 break SSR (webpack with `target: 'node'`), this is because webpack uses `module` entry point from `package.json` but it's should only be used for browser bundle (not server side)

**Comment by pveyes** [comment]
Based on webpack docs: https://webpack.js.org/configuration/resolve/#resolve-mainfields

`target: 'node'` will use `modules` then `main`. This is why SSR will fail because it uses file from `modules` field in `package.json`

It's unfortunate but I think the only solution is removing `modules` field from `package.json` because of the way we bundle things (server & browser module is not compatible)

**Comment by greggb** [comment]
Blargh, that's a bummer. Sorry about the breakage. Hopefully the change from `module.exports` -> `export default` will fix the original uglify issue on its own.

**Comment by pveyes** [comment]
No worries, good thing it was catched via automated e2e test
