### ISSUE TITLE
Typescript Typings

### ISSUE THREAD

**Issue by Arcath** [pveyes/htmr#86]
I notice that htmr is written in typescript but isn't supplying any types for us to use with it in our code.

Is it possible to export the types during the rollup?

I've always used `tsc` to compile my npm modules so they include the typings.

**Comment by pveyes** [comment]
Not sure if it's possible using rollup

Alternatively we could provide `index.d.ts` instead, considering the API surface is small enough

**Comment by pveyes** [comment]
released in `v0.8.0`
